---
name: Bug Report
description: File a bug report to help improve the software
title: '🐞 - '
labels: 'bug-report'

body:
    - type: markdown
      attributes:
          value: '# Reporting a bug'
    - type: markdown
      attributes:
          value: |
              Thank you for helping us make Bloom better, by reporting a bug you have found. This issue may already be reported! Please search on the [issue tracker](https://github.com/maxwellmattryan/apellum.com/issues?q=is%3Aopen+is%3Aissue+label%3Abug-report) before creating one. This form is for bugs only and not for help or support using this application. Please visit the [help and support discussions forum](https://github.com/maxwellmattryan/apellum.com/discussions) for help.

    - type: markdown
      attributes:
          value: '## Application details'

    - type: input
      id: version
      attributes:
          label: Version
          description: What version are you using? (Select all that apply)
          placeholder: "0.1.0"
      validations:
          required: true

    - type: markdown
      attributes:
          value: '## Issue report'

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Briefly describe the issue.
      validations:
          required: true

    - type: textarea
      id: expected_behaviour
      attributes:
          label: Expected behaviour
          description: A concise description of what you expected to happen.
      validations:
          required: true

    - type: textarea
      id: actual_behaviour
      attributes:
          label: Actual behaviour
          description: A concise description of what actually happened.
      validations:
          required: true

    - type: dropdown
      id: can_repro
      attributes:
          label: Can the issue reliably be reproduced?
          options:
              - 'Yes'
              - 'No'
      validations:
          required: true

    - type: textarea
      id: repro_steps
      attributes:
          label: Steps to reproduce the issue
          description: Explain how the maintainer can reproduce the issue.
          placeholder: |
              1.
              2.
              3.
              ...

    - type: markdown
      attributes:
          value: '## Error information'

    - type: textarea
      id: error_messages
      attributes:
          label: Error Messages
          description: Did any error messages display on the screen? If so what was the message?

    - type: textarea
      id: error_logs
      attributes:
          label: Error Logs
          description: Paste the latest errors from the error log, accessible in the Bloom main menu or settings page
          render: shell

    - type: markdown
      attributes:
          value: '## Your machine'

    - type: dropdown
      id: os
      attributes:
          label: Operating System
          description: Which OS does this issue occur on? (Select all that apply)
          multiple: true
          options:
            - Linux
            - Mac
            - Windows
      validations:
          required: true

    - type: markdown
      attributes:
          value: '## Declarations'

    - type: checkboxes
      id: duplicate_declaration
      attributes:
          label: Duplicate declaration
          description: Please confirm that you are not creating a duplicate issue.
          options:
              - label: I have searched the issues tracker this issue and there is none
                required: true
